/**
 * Trusted ClawMon — ERC-8004 Types
 *
 * Type definitions aligned with the ERC-8004 spec (eips.ethereum.org/EIPS/eip-8004).
 * Covers the IdentityRegistry, ReputationRegistry, and the off-chain
 * agent registration / feedback file schemas.
 */

// ---------------------------------------------------------------------------
// Contract Addresses (Monad Testnet)
// ---------------------------------------------------------------------------

export const ERC8004_MONAD_TESTNET = {
  identityRegistry: '0x8004A818BFB912233c491871b3d84c89A494BD9e',
  reputationRegistry: '0x8004B663056A597Dffe9eCcC1965A193B7388713',
} as const;

export const ERC8004_MONAD_MAINNET = {
  identityRegistry: '0x8004A169FB4a3325136EB29fA0ceB6D2e539a432',
  reputationRegistry: '0x8004BAa17C55a88189AE136b182e5fdA19dE9b63',
} as const;

// ---------------------------------------------------------------------------
// Agent Registration File (off-chain JSON at agentURI)
// ---------------------------------------------------------------------------

export interface AgentService {
  name: string;
  endpoint: string;
  version?: string;
  skills?: string[];
  domains?: string[];
}

export interface AgentRegistration {
  agentId: number;
  agentRegistry: string; // e.g. "eip155:10143:0x8004A818..."
}

/**
 * ERC-8004 agent registration file schema.
 * Stored off-chain at the agentURI (IPFS, HTTPS, or data: URI).
 */
export interface AgentRegistrationFile {
  type: 'https://eips.ethereum.org/EIPS/eip-8004#registration-v1';
  name: string;
  description: string;
  image?: string;
  services: AgentService[];
  x402Support: boolean;
  active: boolean;
  registrations: AgentRegistration[];
  supportedTrust?: ('reputation' | 'crypto-economic' | 'tee-attestation')[];
}

// ---------------------------------------------------------------------------
// Proof of Payment (x402 receipt in feedback file)
// ---------------------------------------------------------------------------

/**
 * x402-compatible proof-of-payment included in the off-chain feedback file.
 * This is the receipt that authorizes ERC-8004 feedback submission.
 */
export interface ProofOfPayment {
  fromAddress: string;
  toAddress: string;
  chainId: string;
  txHash: string;
}

// ---------------------------------------------------------------------------
// Feedback File (off-chain JSON at feedbackURI)
// ---------------------------------------------------------------------------

/**
 * ERC-8004 off-chain feedback file schema.
 * Referenced by the feedbackURI parameter in giveFeedback().
 */
export interface FeedbackFile {
  agentRegistry: string;
  agentId: number;
  clientAddress: string;
  createdAt: string; // ISO 8601
  value: number;
  valueDecimals: number;
  tag1?: string;
  tag2?: string;
  endpoint?: string;

  mcp?: { tool?: string; prompt?: string; resource?: string };

  proofOfPayment?: ProofOfPayment;

  /** Execution proof generated by ClawMon proxy */
  executionProof?: {
    outputHash: string;
    clawmonSignature: string;
    timestamp: number;
  };
}

// ---------------------------------------------------------------------------
// On-Chain Feedback (returned by readFeedback / readAllFeedback)
// ---------------------------------------------------------------------------

export interface OnChainFeedback {
  agentId: number;
  clientAddress: string;
  feedbackIndex: number;
  value: number;
  valueDecimals: number;
  tag1: string;
  tag2: string;
  isRevoked: boolean;
}

export interface FeedbackSummary8004 {
  agentId: number;
  count: number;
  summaryValue: number;
  summaryValueDecimals: number;
}

// ---------------------------------------------------------------------------
// Identity metadata entry (for register with metadata)
// ---------------------------------------------------------------------------

export interface MetadataEntry {
  metadataKey: string;
  metadataValue: string; // hex-encoded bytes
}
